/* eslint-disable prettier/prettier */
import { container } from "tsyringe";

import { AdoptionRequestRepository } from "@modules/adoption/repositories/implementations/AdoptionRequestRepository";
import { AdoptionStatusRepository } from "@modules/adoption/repositories/implementations/AdoptionStatusRepository";
import { AnimalHealthRepository } from "@modules/animals/repositories/implementations/AnimalHealthRepository";
import { AnimalPersonalityRepository } from "@modules/animals/repositories/implementations/AnimalPersonalityRepository";
import { AnimalRepository } from "@modules/animals/repositories/implementations/AnimalRepository";
import { AnimalSizesRepository } from "@modules/animals/repositories/implementations/AnimalSizesRepository";
import { CityRepository } from "@modules/adresses/repositories/implementations/CityRepository";
import { IAnimalRepository } from "@modules/animals/repositories/IAnimalRepository";
import { InstitutionAddressRepository } from "@modules/adresses/repositories/implementations/InstitutionAddressRepository";
import { InstitutionAssociateRepository } from "@modules/institutions/repositories/implementations/InstitutionAssociateRepository";
import { InstitutionRepository } from "@modules/institutions/repositories/implementations/InstitutionRepository";
import { ISpecieRepository } from "@modules/animals/repositories/ISpecieRepository";
import { IUsersRepository } from "@modules/accounts/repositories/IUserRepository";
import { RoleRepository } from "@modules/accounts/repositories/implementations/RoleRepository";
import { SpecieRepository } from "@modules/animals/repositories/implementations/SpecieRepository";
import { StageOfLifeRepository } from "@modules/animals/repositories/implementations/StageOfLifeRepository";
import { UfRepository } from "@modules/adresses/repositories/implementations/UfRepository";
import { UsersRepository } from "@modules/accounts/repositories/implementations/UserRepository";
import type { IAdoptionRequestRepository } from "@modules/adoption/repositories/IAdoptionRequestRepository";
import type { IAdoptionStatusRepository } from "@modules/adoption/repositories/IAdoptionStatusRepository";
import type { IAnimalHealthRepository } from "@modules/animals/repositories/IAnimalHealthRepository";
import type { IAnimalPersonalityRepository } from "@modules/animals/repositories/IAnimalPersonalityRepository";
import type { IAnimalSizesRepository } from "@modules/animals/repositories/IAnimalSizeRepository";
import type { ICityRepository } from "@modules/adresses/repositories/ICityRepository";
import type { IInstitutionAddressRepository } from "@modules/adresses/repositories/IInstitutionAddressRepository";
import type { IInstitutionAssociateRepository } from "@modules/institutions/repositories/IInstitutionAssociateRepository";
import type { IInstitutionRepository } from "@modules/institutions/repositories/IInstitutionRepository";
import type { IRoleRepository } from "@modules/accounts/repositories/IRoleRepository";
import type { IStageOfLifeRepository } from "@modules/animals/repositories/IStageOfLifeRepository";
import type { IUfRepository } from "@modules/adresses/repositories/IUfRepository";

container.registerSingleton<IAdoptionRequestRepository>("AdoptionRequestRepository", AdoptionRequestRepository);
container.registerSingleton<IAdoptionStatusRepository>("AdoptionStatusRepository", AdoptionStatusRepository);
container.registerSingleton<IAnimalHealthRepository>("AnimalHealthRepository", AnimalHealthRepository);
container.registerSingleton<IAnimalPersonalityRepository>("AnimalPersonalityRepository", AnimalPersonalityRepository);
container.registerSingleton<IAnimalRepository>("AnimalRepository", AnimalRepository);
container.registerSingleton<IAnimalSizesRepository>("AnimalSizesRepository", AnimalSizesRepository);
container.registerSingleton<ICityRepository>("CityRepository", CityRepository);
container.registerSingleton<IInstitutionAddressRepository>("InstitutionAddressRepository", InstitutionAddressRepository);
container.registerSingleton<IInstitutionAssociateRepository>("InstitutionAssociateRepository", InstitutionAssociateRepository);
container.registerSingleton<IInstitutionRepository>("InstitutionRepository", InstitutionRepository);
container.registerSingleton<IRoleRepository>("RoleRepository", RoleRepository);
container.registerSingleton<ISpecieRepository>("SpecieRepository", SpecieRepository);
container.registerSingleton<IStageOfLifeRepository>("StageOfLifeRepository", StageOfLifeRepository);
container.registerSingleton<IUfRepository>("UfRepository", UfRepository);
container.registerSingleton<IUsersRepository>("UsersRepository", UsersRepository);
